apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: testns
  labels: 
    owner: eman
    webserver: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 90
